package api

import (
	"net/http"
	"time"

	_ "github.com/mkbblr/gopkg/apps/workflow/docs" // docs is generated by Swag CLI, we have to import it.
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

// check ... check workflow data
// @Summary	check api
// @Description	Check and verify workflow data
// @Success 200 {array} WorkflowResponse
// @Failure 404 {object} ErrorResponse
// @Router /check [post]
func Check() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		time.Sleep(10 * time.Second)
		w.Write([]byte("check success !!!\n"))
	})
}

func Doc(url string) http.Handler {
	return httpSwagger.Handler(
		httpSwagger.URL(url), //The url pointing to API definition
	)
}
