package server

import (
	"fmt"
	"net/http"

	"github.com/mkbblr/gopkg/apps/workflow/api"
	_ "github.com/mkbblr/gopkg/apps/workflow/docs" // docs is generated by Swag CLI, we have to import it.
)

type WorkflowServer struct {
}

func (s *WorkflowServer) Run(schema, host string, port int) {

	mux := http.NewServeMux()

	docContentUrl := fmt.Sprintf("%s://%s:%d/doc.json", schema, host, port)

	// both "/" & "/doc" should be added to make "/doc/index.html" work, need to check why
	mux.Handle("/", api.Doc(docContentUrl))
	mux.Handle("/doc/*", api.Doc(docContentUrl))

	// add the actual api
	mux.Handle("/check", api.Authenticate(api.Check()))

	addr := fmt.Sprintf("%s:%d", host, port)
	indexPageURL := fmt.Sprintf("%s://%s:%d/doc/index.html", schema, host, port)

	fmt.Printf("\n Server address: %s\n Documentation link: %s \n\n", addr, indexPageURL)
	http.ListenAndServe(addr, mux)
}
