/*
sample is a server application to demonstrate best practices of api development.
Start the process as

	sample [flags]

The flags are:

	-show, -jsonbi
		Prints build information in JSON format and exit.

	-onelinebi
		Prints short build information in one single line and exit.

	-fullbi
		Prints build information in plain text format ad exit.

	-port=[value]
		Start server on specified port. Default is 8080.
*/
package main

import (
	_ "github.com/mkbblr/gopkg/apps/sample/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/mkbblr/gopkg/apps/sample/server"
)

//go:generate sh -c "$(go env GOPATH)/bin/xbigen"
//go:generate sh -c "$(go env GOPATH)/bin/swag init --md ./"

// swagger header below

// @title sample
// @version 1.0.0
// @description API to showcase best development practices.
// @description.markdown desc.md

// @contact.name API Support
// @contact.url http://www.myorg.io/support
// @contact.email support@myorg.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:5000
// @BasePath /sample
func main() {
	s := &server.SampleServer{}
	s.Run("http", "localhost", 5000)
}
