/*
workflow is a server application that implements apis for workflow management.
Usage:

	workflow [flags]

The flags are:

	-show, -jsonbi
		Prints build information in JSON format and exit.

	-onelinebi
		Prints short build information in one single line and exit.

	-fullbi
		Prints build information in plain text format ad exit.

	-port=[value]
		Start server on specified port. Default is 8080.
*/
package main

import (
	"flag"

	_ "github.com/mkbblr/gopkg/apps/workflow/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/mkbblr/gopkg/apps/workflow/server"
)

//go:generate sh -c "$(go env GOPATH)/bin/xbigen"
//go:generate sh -c "$(go env GOPATH)/bin/swag init --md ./"

var flagPort int

func init() {
	flag.IntVar(&flagPort, "p", 5000, "specify the port on which server shall be started")
}

// swagger header below

// @title workflow
// @version 1.0.0
// @description API to manage and use workflows.
// @description.markdown

// @contact.name API Support
// @contact.url http://www.myorg.io/support
// @contact.email support@myorg.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:5000
// @BasePath /workflow
func main() {
	flag.Parse()
	s := server.WorkflowServer{}
	s.Run("http", "localhost", flagPort)
}
